src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionCategoryListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

/// <summary>
/// Represents a permission category list model
/// </summary>
public partial record PermissionCategoryListModel : BasePagedListModel<PermissionCategoryModel>;

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionCategoryModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

public partial record PermissionCategoryModel : BaseNopModel
{
    public string Name { get; set; }

    public string Text { get; set; }
}

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionCategorySearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

public partial record PermissionCategorySearchModel : BaseSearchModel
{
    #region Ctor

    public PermissionCategorySearchModel()
    {
        PermissionItemSearchModel = new PermissionItemSearchModel();
    }

    #endregion

    #region Properties

    public PermissionItemSearchModel PermissionItemSearchModel { get; set; }

    #endregion
}

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionConfigurationModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

/// <summary>
/// Represents a permission configuration model
/// </summary>
public partial record PermissionConfigurationModel : BaseNopModel
{
    #region Ctor

    public PermissionConfigurationModel()
    {
        PermissionCategorySearchModel = new PermissionCategorySearchModel
        {
            Length = int.MaxValue
        };
    }

    #endregion

    #region Properties

    public bool IsPermissionsAvailable { get; set; }

    public bool AreCustomerRolesAvailable { get; set; }

    public PermissionCategorySearchModel PermissionCategorySearchModel { get; set; }

    #endregion
}

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionItemListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

/// <summary>
/// Represents a permission item list model
/// </summary>
public partial record PermissionItemListModel : BasePagedListModel<PermissionItemModel>;

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionItemModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Web.Areas.Admin.Models.Security;

/// <summary>
/// Represents a permission item model
/// </summary>
public partial record PermissionItemModel : BaseNopEntityModel
{
    #region Ctor

    public PermissionItemModel()
    {
        SelectedCustomerRoleIds = new List<int>();
        AvailableCustomerRoles = new List<SelectListItem>();
    }

    #endregion

    #region Properties

    public string PermissionName { get; set; }

    public string PermissionAppliedFor { get; set; }

    [NopResourceDisplayName("Admin.Customers.CustomerRoles")]
    public IList<int> SelectedCustomerRoleIds { get; set; }

    public IList<SelectListItem> AvailableCustomerRoles { get; set; }

    #endregion
}

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionItemSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

/// <summary>
/// Represents a permission category item search model
/// </summary>
public partial record PermissionItemSearchModel : BaseSearchModel
{
    #region Properties

    public string PermissionCategoryName { get; set; }

    #endregion
}

src/Presentation/Nop.Web/Areas/Admin/Models/Security/PermissionRecordModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Security;

/// <summary>
/// Represents a permission record model
/// </summary>
public partial record PermissionRecordModel : BaseNopModel
{
    #region Properties

    public string Name { get; set; }

    public string SystemName { get; set; }

    #endregion
}

src/Presentation/Nop.Web/Areas/Admin/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Security;
using Nop.Services.Customers;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Security;
using Nop.Web.Framework.Menu;
using Nop.Web.Framework.Mvc.Filters;
using ILogger = Nop.Services.Logging.ILogger;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class SecurityController : BaseAdminController
{
    #region Fields

    protected readonly IAdminMenu _adminMenu;
    protected readonly ICustomerService _customerService;
    protected readonly ILogger _logger;
    protected readonly IPermissionService _permissionService;
    protected readonly ISecurityModelFactory _securityModelFactory;
    protected readonly IWorkContext _workContext;

    private static readonly Dictionary<string, string> _menuSystemNames = new();

    #endregion

    #region Ctor

    public SecurityController(IAdminMenu adminMenu,
        ICustomerService customerService,
        ILogger logger,
        IPermissionService permissionService,
        ISecurityModelFactory securityModelFactory,
        IWorkContext workContext)
    {
        _adminMenu = adminMenu;
        _customerService = customerService;
        _logger = logger;
        _permissionService = permissionService;
        _securityModelFactory = securityModelFactory;
        _workContext = workContext;
    }
    
    #endregion

    #region Methods

    public virtual async Task<IActionResult> AccessDenied(string pageUrl, string pageSystemNameKey)
    {
        if (!_menuSystemNames.Any())
        {
            void fillSystemNames(AdminMenuItem node)
            {
                if (!string.IsNullOrEmpty(node.ControllerName) && !string.IsNullOrEmpty(node.ActionName))
                {
                    var key = $"{node.ControllerName}.{node.ActionName}";
                    _menuSystemNames[key] = node.SystemName;
                }

                foreach (var childNode in node.ChildNodes) 
                    fillSystemNames(childNode);
            }

            fillSystemNames(await _adminMenu.GetRootNodeAsync(true));
        }

        var currentCustomer = await _workContext.GetCurrentCustomerAsync();

        var menuSystemName = "Home";

        if (!string.IsNullOrEmpty(pageSystemNameKey))
        {
            if (_menuSystemNames.TryGetValue(pageSystemNameKey, out var value))
                menuSystemName = value;
            else
            {
                var systemName =
                    _menuSystemNames.FirstOrDefault(item => item.Key.StartsWith(pageSystemNameKey.Split('.')[0]));

                if (!string.IsNullOrEmpty(systemName.Value))
                    menuSystemName = systemName.Value;
            }
        }

        if (currentCustomer == null || await _customerService.IsGuestAsync(currentCustomer))
            await _logger.InformationAsync($"Access denied to anonymous request on {pageUrl}");
        else
            await _logger.InformationAsync($"Access denied to user #{currentCustomer.Id} '{currentCustomer.Email}' on {pageUrl}");

        return View(model: menuSystemName);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> PermissionCategory(PermissionItemSearchModel searchModel)
    {
        var model = await _securityModelFactory.PreparePermissionItemListModelAsync(searchModel);

        return Json(model);
    }

    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> PermissionEditPopup(int id)
    {
        var permissionRecord = await _permissionService.GetPermissionRecordByIdAsync(id);
        var model = await _securityModelFactory.PreparePermissionItemModelAsync(permissionRecord);

        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> PermissionEditPopup(PermissionItemModel model)
    {
        if (ModelState.IsValid)
        {
            var mapping = await _permissionService.GetMappingByPermissionRecordIdAsync(model.Id);

            var rolesForDelete = mapping.Where(p => !model.SelectedCustomerRoleIds.Contains(p.CustomerRoleId))
                .Select(p => p.CustomerRoleId).ToList();

            var rolesToAdd = model.SelectedCustomerRoleIds.Where(p => mapping.All(m => m.CustomerRoleId != p)).ToList();

            foreach (var customerRoleId in rolesForDelete)
                await _permissionService.DeletePermissionRecordCustomerRoleMappingAsync(model.Id, customerRoleId);

            foreach (var customerRoleId in rolesToAdd)
                await _permissionService.InsertPermissionRecordCustomerRoleMappingAsync(new PermissionRecordCustomerRoleMapping
                {
                    PermissionRecordId = model.Id,
                    CustomerRoleId = customerRoleId
                });
            ViewBag.RefreshPage = true;

            var permissionRecord = await _permissionService.GetPermissionRecordByIdAsync(model.Id);

            if (rolesForDelete.Any() || rolesToAdd.Any())
                //for clear cache
                await _permissionService.UpdatePermissionRecordAsync(permissionRecord);


            model = await _securityModelFactory.PreparePermissionItemModelAsync(permissionRecord);

            return View(model);
        }

        //if we got this far, something failed, redisplay form
        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> PermissionCategories(PermissionCategorySearchModel searchModel)
    {
        var model = await _securityModelFactory.PreparePermissionCategoryListModelAsync(searchModel);

        return Json(model);
    }

    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> Permissions()
    {
        //prepare model
        var model = await _securityModelFactory.PreparePermissionConfigurationModelAsync(new PermissionConfigurationModel());

        return View(model);
    }

    #endregion
}

src/Presentation/Nop.Web/Areas/Admin/Views/Security/AccessDenied.cshtml
@model string

@{
    NopHtml.SetActiveMenuItemSystemName(Model);
}

<div class="alert alert-danger alert-dismissable">
    @T("Admin.AccessDenied.Description")
</div>
<div class="content-header">
    <h1>@T("Admin.AccessDenied.Title")</h1>
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/Security/PermissionEditPopup.cshtml
@model PermissionItemModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Configuration.ACL.Permission.Edit").Text;

    @if (ViewBag.RefreshPage == true)
    {
        <script>
            try {
                var el = $(window.opener.document.getElementById('permission-applied-for-@Model.Id'));
                el.html('@Html.Raw(Model.PermissionAppliedFor)');
            }
            catch (e) {
            }
            window.close();
        </script>
    }
}

<form asp-controller="Security" asp-action="PermissionEditPopup">
    <section class="content">
        <div class="container-fluid">
            <div class="content-header clearfix">
                <h1 class="float-left">
                    @T("Admin.Configuration.ACL.Permission.Edit")
                </h1>
                <div class="float-right">
                    <button type="submit" name="save" class="btn btn-primary">
                        <i class="far fa-floppy-disk"></i>
                        @T("Admin.Common.Save")
                    </button>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                </div>
                <div class="col-md-9">
                    @Model.PermissionName
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="SelectedCustomerRoleIds" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="SelectedCustomerRoleIds" asp-items="Model.AvailableCustomerRoles" asp-multiple="true" />
                    <script>
                        $(function () {
                            var rolesIdsInput = $('#@Html.IdFor(model => model.SelectedCustomerRoleIds)').select2({
                                closeOnSelect: false,
                                @if (!Model.AvailableCustomerRoles.Any())
                                {
                                    <text>
                                        disabled: true,
                                        placeholder: '@T("Admin.Configuration.ACL.NoCustomerRolesAvailable")',
                                    </text>
                                }
                            });

                            $('#@Html.IdFor(model => model.SelectedCustomerRoleIds)').on('select2:open', function (e) {
                                const container = $(this).siblings('.select2-container');
                                const availableHeight = $(window).height() - container.offset().top - container.outerHeight() - 1;
                                $('ul.select2-results__options').css('max-height', Math.max(availableHeight, 50) + 'px');
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </section>
</form>

src/Presentation/Nop.Web/Areas/Admin/Views/Security/Permissions.cshtml
@model PermissionConfigurationModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.ACL").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Access control list");
}

<style type="text/css">
    table.dataTable.table-hover>tbody>tr:hover>*{box-shadow:inset 0 0 0 9999px rgba(255, 255, 255, 1)}

    table.dataTable.table-striped>tbody>tr.odd>*{box-shadow:inset 0 0 0 9999px rgba(0, 0, 0, 0.05)}
</style>

<script type="text/javascript">     
    $(function () {
        $('#permissions-grid').on( 'init.dt', function () {
            $('tr').css('bg-color', 'white');
        } );
    });
</script>

<form asp-controller="Security" asp-action="Permissions" method="post" id="permissions-form">
    <div class="content-header clearfix">
        <div class="float-right">
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.PermissionListButtons, additionalData = Model })
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    <div class="card card-default">
                        <div class="card-body">
                            <p>
                                @T("Admin.Configuration.ACL.Description")
                                <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.Acl", Docs.Acl + Utm.OnAdmin)" asp-add-wrapper="false" />
                            </p>
                            @if (!Model.IsPermissionsAvailable)
                            {
                                <text>@T("Admin.Configuration.ACL.NoPermissionsDefined")</text>
                            }
                            else if (!Model.AreCustomerRolesAvailable)
                            {
                                <text>@T("Admin.Configuration.ACL.NoCustomerRolesAvailable")</text>
                            }
                            else
                            {
                                <div class="scroll-wrapper">
                                    @await Html.PartialAsync("Table", new DataTablesModel
                                    {
                                        Name = "permissions-grid",
                                        RefreshButton = false,
                                        UrlRead = new DataUrl("PermissionCategories", "Security", null),
                                        PrimaryKeyColumn = nameof(PermissionCategoryModel.Name),
                                        Length = Model.PermissionCategorySearchModel.PageSize,
                                        ColumnCollection = new List<ColumnProperty>
                                        {
                                            new(null)
                                            {
                                                Render = new RenderChildCaret(),
                                                Width = "5",
                                                Searchable = false,
                                                ClassName = NopColumnClassDefaults.ChildControl
                                            },
                                            new(nameof(PermissionCategoryModel.Name))
                                            {
                                                Title = T("Admin.Configuration.ACL.Permission.CategoryName").Text,
                                                Render = new RenderCustom("renderPermissionCategory")
                                            }
                                        },
                                        ChildTable = new DataTablesModel
                                        {
                                            Name = "permission-items-grid",
                                            UrlRead = new DataUrl("PermissionCategory", "Security", null),
                                            IsChildTable = true,
                                            Length = Model.PermissionCategorySearchModel.PageSize,
                                            LengthMenu = Model.PermissionCategorySearchModel.AvailablePageSizes,
                                            Filters = new List<FilterParameter>
                                            {
                                                new(nameof(PermissionItemSearchModel.PermissionCategoryName), nameof(PermissionCategoryModel.Name), true)
                                            },
                                            ColumnCollection = new List<ColumnProperty>
                                            {
                                                new(nameof(PermissionItemModel.PermissionName))
                                                {
                                                    Title = T("Admin.Configuration.ACL.Permission.PermissionName").Text, 
                                                    Width = "400px"
                                                },
                                                new(nameof(PermissionItemModel.PermissionAppliedFor))
                                                {
                                                    Title = T("Admin.Customers.CustomerRoles").Text,
                                                    AutoWidth = true,
                                                    Render = new RenderCustom("renderPermissionText")
                                                },
                                                new(nameof(PermissionItemModel.Id))
                                                {
                                                    Title = T("Admin.Common.Edit").Text,
                                                    Width = "100px",
                                                    ClassName = NopColumnClassDefaults.Button,
                                                    Render = new RenderCustom("renderPermissionEdit")
                                                },
                                            }
                                        }
                                    })
                                    <script>
                                        function renderPermissionEdit(data, type, row, meta) {
                                            return '<button onclick=\"javascript:OpenWindow(\'@Url.Content("~/Admin/Security/PermissionEditPopup/")' + data + '\', 800, 300, true); return false;\" class="btn btn-default"><i class="fas fa-pencil"></i>@T("Admin.Common.Edit").Text</button>';
                                        }
                                        function renderPermissionText(data, type, row, meta) {                                            
                                            return '<span id="permission-applied-for-' + row.Id + '">' + data + '</span>';
                                        }
                                        function renderPermissionCategory(data, type, row, meta) {
                                            return row.Text;
                                        }                                        
                                    </script>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>