src/Presentation/Nop.Web/Areas/Admin/Controllers/NewsLetterSubscriptionController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Messages;
using Nop.Services.ExportImport;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Messages;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class NewsLetterSubscriptionController : BaseAdminController
{
    #region Fields

    protected readonly IDateTimeHelper _dateTimeHelper;
    protected readonly IExportManager _exportManager;
    protected readonly IImportManager _importManager;
    protected readonly ILocalizationService _localizationService;
    protected readonly INewsLetterSubscriptionModelFactory _newsletterSubscriptionModelFactory;
    protected readonly INewsLetterSubscriptionService _newsLetterSubscriptionService;
    protected readonly INewsLetterSubscriptionTypeService _newsLetterSubscriptionTypeService;
    protected readonly INotificationService _notificationService;
    protected readonly IPermissionService _permissionService;

    #endregion

    #region Ctor

    public NewsLetterSubscriptionController(IDateTimeHelper dateTimeHelper,
        IExportManager exportManager,
        IImportManager importManager,
        ILocalizationService localizationService,
        INewsLetterSubscriptionModelFactory newsletterSubscriptionModelFactory,
        INewsLetterSubscriptionService newsLetterSubscriptionService,
        INewsLetterSubscriptionTypeService newsLetterSubscriptionTypeService,
        INotificationService notificationService,
        IPermissionService permissionService)
    {
        _dateTimeHelper = dateTimeHelper;
        _exportManager = exportManager;
        _importManager = importManager;
        _localizationService = localizationService;
        _newsletterSubscriptionModelFactory = newsletterSubscriptionModelFactory;
        _newsLetterSubscriptionService = newsLetterSubscriptionService;
        _newsLetterSubscriptionTypeService = newsLetterSubscriptionTypeService;
        _notificationService = notificationService;
        _permissionService = permissionService;
    }

    #endregion

    #region Methods

    public virtual IActionResult Index()
    {
        return RedirectToAction("List");
    }

    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_VIEW)]
    public virtual async Task<IActionResult> List()
    {
        //prepare model
        var model = await _newsletterSubscriptionModelFactory.PrepareNewsLetterSubscriptionSearchModelAsync(new NewsLetterSubscriptionSearchModel());

        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_VIEW)]
    public virtual async Task<IActionResult> List(NewsLetterSubscriptionSearchModel searchModel)
    {
        //prepare model
        var model = await _newsletterSubscriptionModelFactory.PrepareNewsLetterSubscriptionListModelAsync(searchModel);

        return Json(model);
    }

    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_CREATE_EDIT_DELETE)]
    public virtual async Task<IActionResult> Create()
    {
        //prepare model
        var model = await _newsletterSubscriptionModelFactory.PrepareNewsLetterSubscriptionModelAsync(new NewsLetterSubscriptionModel(), null);

        return View(model);
    }

    [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_CREATE_EDIT_DELETE)]
    public virtual async Task<IActionResult> Create(NewsLetterSubscriptionModel model, bool continueEditing)
    {
        if (ModelState.IsValid)
        {
            var subscription = model.ToEntity<NewsLetterSubscription>();

            subscription.TypeId = model.SelectedNewsLetterSubscriptionTypeId;
            subscription.StoreId = model.SelectedNewsLetterSubscriptionStoreId;
            subscription.LanguageId = model.SelectedNewsLetterSubscriptionLanguageId;

            var subscriptionsByEmail = await _newsLetterSubscriptionService
                .GetNewsLetterSubscriptionsByEmailAsync(subscription.Email, storeId: subscription.StoreId);
            var availableSubscriptionTypes = await _newsLetterSubscriptionTypeService.GetAllNewsLetterSubscriptionTypesAsync(subscription.StoreId);

            var existingSubscription = subscriptionsByEmail.FirstOrDefault(s => s.TypeId == subscription.TypeId);
            if (existingSubscription == null && availableSubscriptionTypes.Any(x => x.Id == subscription.TypeId))
            {
                subscription.NewsLetterSubscriptionGuid = subscriptionsByEmail.FirstOrDefault()?.NewsLetterSubscriptionGuid ?? Guid.NewGuid();
                subscription.CreatedOnUtc = DateTime.UtcNow;
                await _newsLetterSubscriptionService.InsertNewsLetterSubscriptionAsync(subscription);
                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Promotions.NewsLetterSubscription.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = subscription.Id }) : RedirectToAction("List");
            }
            else
            {
                _notificationService.WarningNotification(await _localizationService.GetResourceAsync("Admin.Promotions.NewsLetterSubscription.Warning"));
            }
        }

        //prepare model
        model = await _newsletterSubscriptionModelFactory.PrepareNewsLetterSubscriptionModelAsync(model, null, true);

        //if we got this far, something failed, redisplay form
        return View(model);
    }

    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_CREATE_EDIT_DELETE)]
    public virtual async Task<IActionResult> Edit(int id)
    {
        var subscription = await _newsLetterSubscriptionService.GetNewsLetterSubscriptionByIdAsync(id);
        if (subscription == null)
            return RedirectToAction("List");

        //prepare model
        var model = await _newsletterSubscriptionModelFactory.PrepareNewsLetterSubscriptionModelAsync(null, subscription);

        return View(model);
    }

    [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_CREATE_EDIT_DELETE)]
    public virtual async Task<IActionResult> Edit(NewsLetterSubscriptionModel model, bool continueEditing)
    {
        var subscription = await _newsLetterSubscriptionService.GetNewsLetterSubscriptionByIdAsync(model.Id);
        if (subscription == null)
            return RedirectToAction("List");

        if (ModelState.IsValid)
        {
            //fill entity from model
            subscription = model.ToEntity(subscription);

            subscription.TypeId = model.SelectedNewsLetterSubscriptionTypeId;
            subscription.LanguageId = model.SelectedNewsLetterSubscriptionLanguageId;
            subscription.StoreId = model.SelectedNewsLetterSubscriptionStoreId;

            var currentSubscription = (await _newsLetterSubscriptionService
                .GetNewsLetterSubscriptionsByEmailAsync(subscription.Email, storeId: subscription.StoreId, subscriptionTypeId: subscription.TypeId))
                .FirstOrDefault();

            var availableSubscriptionTypes = await _newsLetterSubscriptionTypeService.GetAllNewsLetterSubscriptionTypesAsync(subscription.StoreId);
            var isAvailableSubscriptionType = availableSubscriptionTypes.Any(x => x.Id == subscription.TypeId);

            if ((currentSubscription == null || (currentSubscription.Id == subscription.Id)) && isAvailableSubscriptionType)
            {
                await _newsLetterSubscriptionService.UpdateNewsLetterSubscriptionAsync(subscription);
                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Promotions.NewsLetterSubscription.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = subscription.Id }) : RedirectToAction("List");
            }
            else
            {
                _notificationService.WarningNotification(await _localizationService.GetResourceAsync("Admin.Promotions.NewsLetterSubscription.Warning"));
            }
        }

        //prepare model
        model = await _newsletterSubscriptionModelFactory.PrepareNewsLetterSubscriptionModelAsync(model, subscription, true);

        //if we got this far, something failed, redisplay form
        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_CREATE_EDIT_DELETE)]
    public virtual async Task<IActionResult> Delete(int id)
    {
        var subscription = await _newsLetterSubscriptionService.GetNewsLetterSubscriptionByIdAsync(id);
        if (subscription == null)
            return RedirectToAction("List");

        try
        {
            await _newsLetterSubscriptionService.DeleteNewsLetterSubscriptionAsync(subscription);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Promotions.NewsLetterSubscription.Deleted"));

            return RedirectToAction("List");
        }
        catch (Exception exc)
        {
            await _notificationService.ErrorNotificationAsync(exc);
            return RedirectToAction("Edit", new { id = subscription.Id });
        }
    }

    #region Export/Import

    [HttpPost, ActionName("ExportCSV")]
    [FormValueRequired("exportcsv")]
    [CheckPermission(StandardPermission.Promotions.SUBSCRIBERS_IMPORT_EXPORT)]
    public virtual async Task<IActionResult> ExportCsv(NewsLetterSubscriptionSearchModel model)
    {
        bool? isActive = null;
        if (model.ActiveId == 1)
            isActive = true;
        else if (model.ActiveId == 2)
            isActive = false;

src/Presentation/Nop.Web/Areas/Admin/Views/NewsLetterSubscription/Create.cshtml
@model NewsLetterSubscriptionModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Promotions.NewsLetterSubscription.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Newsletter subscriptions");
}

<form asp-controller="NewsLetterSubscription" asp-action="Create" method="post" id="subscription-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Promotions.NewsLetterSubscription.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Promotions.NewsLetterSubscription.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.NewsLetterSubscriptionButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

src/Presentation/Nop.Web/Areas/Admin/Views/NewsLetterSubscription/Edit.cshtml
@model NewsLetterSubscriptionModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Promotions.NewsLetterSubscription.EditSubscriptionDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Newsletter subscriptions");
}

<form asp-controller="NewsLetterSubscription" asp-action="Edit" method="post" id="subscription-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Promotions.NewsLetterSubscription.EditSubscriptionDetails") - @Model.Email
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Promotions.NewsLetterSubscription.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="subscription-delete" class="btn btn-danger">
                <i class="far fa-trash-can"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.NewsLetterSubscriptionButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="subscription-delete" />

src/Presentation/Nop.Web/Areas/Admin/Views/NewsLetterSubscription/List.cshtml
@model NewsLetterSubscriptionSearchModel

@using Nop.Services.Stores

@inject IStoreService storeService

@{
    //page title
    ViewBag.PageTitle = T("Admin.Promotions.newsLetterSubscriptions").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Newsletter subscriptions");
}

@{
    const string hideSearchBlockAttributeName = "NewsletterSubscriptionPage.HideSearchBlock";
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(await workContext.GetCurrentCustomerAsync(), hideSearchBlockAttributeName);
}

<form asp-controller="NewsLetterSubscription" asp-action="List" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Promotions.NewsLetterSubscriptions")
        </h1>
        <div class="float-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fas fa-square-plus"></i>
                @T("Admin.Common.AddNew")
            </a>
            <button asp-action="ExportCSV" type="submit" name="exportcsv" class="btn btn-success">
                <i class="fas fa-download"></i>
                @T("Admin.Common.ExportToCsv")
            </button>
            <button type="button" name="importcsv" class="btn bg-olive" data-toggle="modal" data-target="#importcsv-window">
                <i class="fas fa-upload"></i>
                @T("Admin.Common.ImportFromCsv")
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.NewsLetterSubscriptionListButtons, additionalData = Model })
        </div>
    </div>

    <section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                <div class="card card-default card-search">
                    <div class="card-body">
                        <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                            <div class="search-text">@T("Admin.Common.Search")</div>
                            <div class="icon-search"><i class="fas fa-magnifying-glass" aria-hidden="true"></i></div>
                            <div class="icon-collapse"><i class="far fa-angle-@(!hideSearchBlock ? "up" : "down")" aria-hidden="true"></i></div>
                        </div>

                        <div class="search-body @(hideSearchBlock ? "closed" : "")">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="SearchEmail" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-editor asp-for="SearchEmail" />
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="StartDate" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-editor asp-for="StartDate" />
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="EndDate" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-editor asp-for="EndDate" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="ActiveId" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-select asp-for="ActiveId" asp-items="Model.ActiveList" />
                                        </div>
                                    </div>
                                    <div class="form-group row" @(Model.HideStoresList ? Html.Raw("style=\"display:none\"") : null)>
                                        <div class="col-md-4">
                                            <nop-label asp-for="StoreId" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-select asp-for="StoreId" asp-items="Model.AvailableStores" />
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="CustomerRoleId" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-select asp-for="CustomerRoleId" asp-items="Model.AvailableCustomerRoles" />
                                        </div>
                                    </div>
                                        <div class="form-group row">
                                            <div class="col-md-4">
                                                <nop-label asp-for="SubscriptionTypeId" />
                                            </div>
                                            <div class="col-md-8">
                                                <nop-select asp-for="SubscriptionTypeId" asp-items="Model.AvailableSubscriptionTypes" />
                                            </div>
                                        </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="text-center col-12">
                                    <button type="button" id="search-subscriptions" class="btn btn-primary btn-search">
                                        <i class="fas fa-magnifying-glass"></i>
                                        @T("Admin.Common.Search")
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card card-default">
                    <div class="card-body">
                        <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.EmailCampaigns", Docs.EmailCampaigns + Utm.OnAdmin)" />

                        @await Html.PartialAsync("Table", new DataTablesModel
                        {
                            Name = "newsletter-subscriptions-grid",
                            UrlRead = new DataUrl("List", "NewsLetterSubscription", null),
                            SearchButtonId = "search-subscriptions",
                            Length = Model.PageSize,
                            LengthMenu = Model.AvailablePageSizes,
                            Filters = new List<FilterParameter>
                            {
                                new FilterParameter(nameof(Model.StartDate), typeof(DateTime?)),
                                new FilterParameter(nameof(Model.EndDate), typeof(DateTime?)),
                                new FilterParameter(nameof(Model.SearchEmail)),
                                new FilterParameter(nameof(Model.ActiveId)),
                                new FilterParameter(nameof(Model.StoreId)),
                                new FilterParameter(nameof(Model.CustomerRoleId)),
                                new FilterParameter(nameof(Model.SubscriptionTypeId))
                            },
                            ColumnCollection = new List<ColumnProperty>
                                {
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.Email))
                                    {
                                        Title = T("Admin.Promotions.NewsLetterSubscription.Fields.Email").Text,
                                        Width = "300",
                                        Editable = true,
                                        EditType = EditType.String
                                    },
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.SubscriptionTypeName))
                                    {
                                        Title = T("Admin.Promotions.NewsLetterSubscription.Fields.SubscriptionType").Text,
                                        Width = "100"
                                    },
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.Active))
                                    {
                                        Title = T("Admin.Promotions.NewsLetterSubscription.Fields.Active").Text,
                                        Width = "100",
                                        ClassName = NopColumnClassDefaults.CenterAll,
                                        Render = new RenderBoolean(),
                                        Editable = true,
                                        EditType = EditType.Checkbox
                                    },
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.StoreName))
                                    {
                                        Title = T("Admin.Promotions.NewsLetterSubscription.Fields.Store").Text,
                                        Width = "150",
                                        Visible = (await storeService.GetAllStoresAsync()).Count > 1
                                    },
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.LanguageName))
                                    {
                                        Title = T("Admin.Promotions.NewsLetterSubscription.Fields.Language").Text,
                                        Width = "150"
                                    },
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.CreatedOn))
                                    {
                                        Title = T("Admin.Promotions.NewsLetterSubscription.Fields.CreatedOn").Text,
                                        Width = "200"
                                    },
                                    new ColumnProperty(nameof(NewsLetterSubscriptionModel.Id))
                                    {
                                        Title = T("Admin.Common.Edit").Text,
                                        Width = "200",
                                        ClassName =  NopColumnClassDefaults.Button,
                                        Render = new RenderButtonEdit(new DataUrl("~/Admin/NewsLetterSubscription/Edit/"))
                                    }                                    
                                }
                        })
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</form>

@*import emails form*@
<div id="importcsv-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="importcsv-window-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="importcsv-window-title">@T("Admin.Common.ImportFromCsv")</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>                
            </div>
            <form asp-controller="NewsLetterSubscription" asp-action="ImportCsv" method="post" enctype="multipart/form-data">
                <div class="form-horizontal">
                    <div class="modal-body">
                        <div class="form-group row">
                            <div class="col-md-2">
                                <div class="label-wrapper">
                                    <label class="col-form-label">
                                        @T("Admin.Common.CsvFile")
                                    </label>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <input type="file" id="importcsvfile" name="importcsvfile" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">
                            @T("Admin.Common.ImportFromCsv")
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>